My first pull request
yasinabdmahmood/Hello-Microverse pull request #1
Opened 2022-06-28 19:02 UTC by yasinabdmahmood

I followed all the instructions to set up a professional repo according to Microverse standards.

2022-06-28 19:15 UTC, zieeco requested changes
Hi, @yasinabdmahmood, 

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Great start :+1: 
- Descriptive PR :+1: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 19:15 UTC, zieeco commented on .gitignore
> +.hintrc
- Please, kindly remove the `.stylelintrc.json` and `.hintrc` from the `.gitignore` file as these files needs to be visible in your repo.

2022-06-28 19:15 UTC, zieeco commented on README.md
> +* Twitter: [@YASEEN30093859](https://twitter.com/yasenabd7)
**[REQUIRED CHANGES]**

- Please, kindly update and add the following missing headers from the [microverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md)

1. Getting started: In this header, you should add some instructions on how a user can have your repo locally on their machine. (hot to clone the repo, how to move into the cloned repo), 
2. Prerequisite: e.g `vscode editor`, a `web browser(chrome, etc)`.
3. Contribution header.
4. Show your support header.
5. Acknowledgments.
6. License.
:point_right: The arrangement should follow that use in the [microverse readme tamplate](https://github.com/microverseinc/readme-template/blob/master/README.md) to keep consistency to make your repo appear professional.

*LINTER*
- As it's a requirement for all projects in microverse, please kindly sure your repo has no linter error.

2022-06-29 08:04 UTC, Ginohmk approved these changes
Hi @yasinabdmahmood , 

# STATUS: APPROVED 🟢

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 08:48 UTC, merged

2022-07-04 09:43 UTC, HAMMAS-SALEEM reviewed
# Status: Approved :green_circle:

Your project is complete. There is nothing else to say about that. :+1:
Go ahead and merge it :muscle:

## [Optional Changes]
### 1. 
![title](https://user-images.githubusercontent.com/93039359/177128601-b34cbcc4-3092-4bfb-a986-5414b954ae1c.png)

- [ ] Your PR has a title that is not so descriptive enough. Because **My first pull request** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Portfolio: setup and mobile version skeleton** for your PR title. :+1:

### 2
#### Your Summary
![branch-name](https://user-images.githubusercontent.com/93039359/177128519-7b3e53b2-4db9-4266-ac8c-3283ffa976d2.png)

#### Descriptive Summary Example :heavy_check_mark:
![clinton summary](https://user-images.githubusercontent.com/93039359/177128798-9e42f1a8-50de-487a-8aa1-0e1d4e2e35de.png)



- [ ] You don't have a summary for your project. You can see the image above to get an idea of what a descriptive summary looks like. The summary tells in detail what are you doing in this pull request and why. :thinking:

### 3.
- [ ] Your branch name is not descriptive enough. You are using **feature-branch**, you can use  **feature/portfolio-mobile-structure** :+1:

### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._